FROM ubuntu:focal

RUN apt-get update
RUN apt-get install -y git && apt-get install -y python3-pip

RUN pip install opencv-contrib-python

RUN git clone https://github.com/QuentinDervin/opencv-repo.git

#RUN pip install caer -----------? useful?

